//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Insurances = new HashSet<Insurance>();
        }
    
        public int CustomerID { get; set; }
        public string EFSalesRefCode { get; set; }
        public string SalesRefNumber { get; set; }
        public string HomeCountryCode { get; set; }
        public bool IsDeleted { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string HomeAddress1 { get; set; }
        public string HomeAddress2 { get; set; }
        public string HomeAddress3 { get; set; }
        public string HomeCity { get; set; }
        public string HomeProvince { get; set; }
        public string HomePostalCode { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Sex { get; set; }
        public string Email { get; set; }
        public string CustomerNotes { get; set; }
        public string CustomerNotesExt { get; set; }
        public bool Reported { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insurance> Insurances { get; set; }
    }
}
