//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TorEntities : DbContext
    {
        public TorEntities()
            : base("name=TorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TorUser> TorUsers { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Insurance> Insurances { get; set; }
    
        public virtual ObjectResult<SearchCustomer_p_Result> SearchCustomer_p(string efSalesRefId, string lastName, string firstName, string startYear, string startMonth, string startDay, string endYear, string endMonth, string endDay, string dobYear, string dobMonth, string dobDay, string salesCountry, string program, string destinationCountry, string policy, string aetnaId)
        {
            var efSalesRefIdParameter = efSalesRefId != null ?
                new ObjectParameter("EfSalesRefId", efSalesRefId) :
                new ObjectParameter("EfSalesRefId", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var startYearParameter = startYear != null ?
                new ObjectParameter("StartYear", startYear) :
                new ObjectParameter("StartYear", typeof(string));
    
            var startMonthParameter = startMonth != null ?
                new ObjectParameter("StartMonth", startMonth) :
                new ObjectParameter("StartMonth", typeof(string));
    
            var startDayParameter = startDay != null ?
                new ObjectParameter("StartDay", startDay) :
                new ObjectParameter("StartDay", typeof(string));
    
            var endYearParameter = endYear != null ?
                new ObjectParameter("EndYear", endYear) :
                new ObjectParameter("EndYear", typeof(string));
    
            var endMonthParameter = endMonth != null ?
                new ObjectParameter("EndMonth", endMonth) :
                new ObjectParameter("EndMonth", typeof(string));
    
            var endDayParameter = endDay != null ?
                new ObjectParameter("EndDay", endDay) :
                new ObjectParameter("EndDay", typeof(string));
    
            var dobYearParameter = dobYear != null ?
                new ObjectParameter("DobYear", dobYear) :
                new ObjectParameter("DobYear", typeof(string));
    
            var dobMonthParameter = dobMonth != null ?
                new ObjectParameter("DobMonth", dobMonth) :
                new ObjectParameter("DobMonth", typeof(string));
    
            var dobDayParameter = dobDay != null ?
                new ObjectParameter("DobDay", dobDay) :
                new ObjectParameter("DobDay", typeof(string));
    
            var salesCountryParameter = salesCountry != null ?
                new ObjectParameter("SalesCountry", salesCountry) :
                new ObjectParameter("SalesCountry", typeof(string));
    
            var programParameter = program != null ?
                new ObjectParameter("Program", program) :
                new ObjectParameter("Program", typeof(string));
    
            var destinationCountryParameter = destinationCountry != null ?
                new ObjectParameter("DestinationCountry", destinationCountry) :
                new ObjectParameter("DestinationCountry", typeof(string));
    
            var policyParameter = policy != null ?
                new ObjectParameter("Policy", policy) :
                new ObjectParameter("Policy", typeof(string));
    
            var aetnaIdParameter = aetnaId != null ?
                new ObjectParameter("AetnaId", aetnaId) :
                new ObjectParameter("AetnaId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchCustomer_p_Result>("SearchCustomer_p", efSalesRefIdParameter, lastNameParameter, firstNameParameter, startYearParameter, startMonthParameter, startDayParameter, endYearParameter, endMonthParameter, endDayParameter, dobYearParameter, dobMonthParameter, dobDayParameter, salesCountryParameter, programParameter, destinationCountryParameter, policyParameter, aetnaIdParameter);
        }
    }
}
