//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TorUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TorUser()
        {
            this.Tokens = new HashSet<Token>();
        }
    
        public int TorUserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public string Type { get; set; }
        public string Rights { get; set; }
        public bool IsDeleted { get; set; }
        public string StartPage { get; set; }
        public string DateFormat { get; set; }
        public string RecordsPerPageClRL { get; set; }
        public string RecordsPerPageCuRL { get; set; }
        public int RecordSetsClaimSection { get; set; }
        public int RecordSetsCustomerSection { get; set; }
        public int RecordsSearchClaimSection { get; set; }
        public int RecordsSearchCustomerSection { get; set; }
        public string LoginName { get; set; }
        public string IPAddress { get; set; }
        public bool AllowAllocationAccess { get; set; }
        public int FailedLoginAttempts { get; set; }
        public bool AllowClaimImportDelete { get; set; }
        public bool AllowCustomerDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Token> Tokens { get; set; }
    }
}
